# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Optimisation procedure
#'
#' @description Example of gradient and stochastic gradient descent method for minimising the sum of squares.
#'
#' @param X Design matrix.
#' @param y Response.
#' @param theta_initial The initial choice of theta.
#' @param alpha The step size.
#' @param tolerance The tolerance imposed on the absolute difference.
#' @param max_iterations The maximum number of iterations.
#' @param trace_limit When should the trace be displayed.
#' @param trace TRUE/FALSE: Should the trace be shown?
#'
#' @return The estimated paramters.
#' @example inst/examples/sgd.R
gd <- function(X, y, theta_initial, alpha, tolerance, max_iterations, trace_limit, trace) {
    .Call(`_SGD_gd`, X, y, theta_initial, alpha, tolerance, max_iterations, trace_limit, trace)
}

#' @title Stochastic gradient descent
#'
#' @description Example of stochastic gradient descent method for minimising the sum of squares.
#'
#' @param X Design matrix.
#' @param y Response.
#' @param theta_initial The initial choice of theta.
#' @param alpha The step size.
#' @param gamma The belief in the current momentum.
#' @param sgd_iterations The number of iterations used, when utilising stochastic gradiend descent.
#' @param trace_limit When should the trace be displayed.
#' @param trace TRUE/FALSE: Should the trace be shown?
#'
#' @return The estimated paramters.
#' @example inst/examples/sgd.R
sgd <- function(X, y, theta_initial, alpha, gamma, sgd_iterations, trace_limit, trace) {
    .Call(`_SGD_sgd`, X, y, theta_initial, alpha, gamma, sgd_iterations, trace_limit, trace)
}

